apiVersion: v1
kind: ConfigMap
metadata:
  name: nfd-worker
data:
  nfd-worker-conf: |
    #uncomment to configure
    #sources:
    #  pci:
    #    deviceClassWhitelist:
    #      - "0200"
    #      - "03"
    #      - "12"
    #    deviceLabelFields:
    #      - "class"
    #      - "vendor"
    #      - "device"
    #      - "subsystem_vendor"
    #      - "subsystem_device"
